language: python

python:
  - 3.8
  - 3.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - python app.test.py
  - flake8 --exclude env --ignore E402,E501 .
  - black --exclude=env .
